### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by jzhou3700** [librahu/HERec#23]
为什么我跑你的代码，结果远远没有论文中说的那么好。基本上只能达到0.8多一些。

**Comment by wdtttt** [comment]
> 为什么我跑你的代码，结果远远没有论文中说的那么好。基本上只能达到0.8多一些。

Traceback (most recent call last):
ratedim:  10  userdim:  30  itemdim:  10
max_steps:  100
  File "C:/Users/wdt13/PycharmProjects/HERec-master/code/HERec_sl.py", line 252, in <module>
delta:  0.02 beta_e:  0.1 beta_h:  0.1 beta_p:  2 beta_w:  0.1 beta_b 0.01 reg_u 1.0 reg_v 1.0
    HNERec(unum, inum, ratedim, userdim, itemdim, user_metapaths, item_metapaths, trainfile, testfile, steps, delta, beta_e, beta_h, beta_p, beta_w, beta_b, reg_u, reg_v)
  File "C:/Users/wdt13/PycharmProjects/HERec-master/code/HERec_sl.py", line 29, in __init__
    self.X, self.user_metapathdims = self.load_embedding(user_metapaths, unum)
  File "C:/Users/wdt13/PycharmProjects/HERec-master/code/HERec_sl.py", line 53, in load_embedding
    with open(sourcefile) as infile:
FileNotFoundError: [Errno 2] No such file or directory: '../data/embeddings/ubu_0.8.embedding'
麻烦问下您有遇到这个问题吗..这个怎么解决，麻烦您指教一下

**Comment by Wql2017** [comment]
@wdtttt FileNotFoundError: [Errno 2] No such file or directory: '../data/embeddings/ubu_0.8.embedding',你看看这个目录下没有这个文件。

**Comment by Hanyuzhen0826** [comment]
> FileNotFoundError： [Errno 2] 没有这样的文件或目录： '../data/embeddings/ubu_0.8.embedding'，你看看这个目录下没有这个文件。

下载之后并且按照readme中运行前三个文件都没有生成这个ubu_0.8.embedding，请问是怎么解决的？
