### ISSUE TITLE
running code

### ISSUE THREAD

**Issue by Shodowelf** [librahu/HERec#6]
Hellow,sir.
In the process of running the program,I encountered the following questions,can you give me an answer?
train_rate:  0.8
ratedim:  10  userdim:  30  itemdim:  10
max_steps:  100
delta:  0.02 beta_e:  0.1 beta_h:  0.1 beta_p:  2 beta_w:  0.1 beta_b 0.1 reg_u 1.0 reg_v 1.0
Traceback (most recent call last):
  File "E:/ler/HERec-master/code/HERec_spl.py", line 261, in <module>
    HNERec(unum, inum, ratedim, userdim, itemdim, user_metapaths, item_metapaths, trainfile, testfile, steps, delta, beta_e, beta_h, beta_p, beta_w, beta_b, reg_u, reg_v)
  File "E:/ler/HERec-master/code/HERec_spl.py", line 29, in __init__
    self.X, self.user_metapathdims = self.load_embedding(user_metapaths, unum)
  File "E:/ler/HERec-master/code/HERec_spl.py", line 53, in load_embedding
    with open(sourcefile) as infile:
FileNotFoundError: [Errno 2] No such file or directory: '../data/embedding/ubu_0.8.embedding'

Process finished with exit code 1
Thank you,very much.

**Comment by librahu** [comment]
The cause of his error is that our code doesn't find the embedding file. You need generate metapaths and embeddings before you run this code. Please follow the step in the readme, and make sure the correctness of the file paths.

**Comment by Shodowelf** [comment]
When I follow the step , I still don't run the code.I want to ask you if I need change your code when I run the code or my run environment is false.

**Comment by librahu** [comment]
What issues did you meet with

**Comment by Shodowelf** [comment]
The metapathGeneration is ok,this is my result.
/usr/bin/python2.7 /home/zhen/HER/HERec-master/code/metapathGeneration.py
UMU...
(16240, 16240)
writing to file...
total =  7887082
UBCaBU...
writing to file...
total =  185577452
UBCiBU...
writing to file...
total =  148164084
MUM...
(14285, 14285)
writing to file...
total =  6992632
BCiB..
writing to file...
total =  37266872
BCaB..
writing to file...
total =  42606494

Process finished with exit code 0

But when I run embeddingGeneration it has error

**Comment by Shodowelf** [comment]
/usr/bin/python2.7 /home/zhen/HER/HERec-master/code/embeddingGeneration.py
deepwalk --format edgelist --input ../data/metapaths/ubu_0.8 --output ../data/embeddings/ubu_0.8 --walk-length 5 --window-size 3 --number-walks 10 --representation-size 128
Traceback (most recent call last):
  File "/usr/local/bin/deepwalk", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 162, in main
    process(args)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 54, in process
    G = graph.load_edgelist(args.input, undirected=args.undirected)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/graph.py", line 249, in load_edgelist
    with open(file_) as f:
IOError: [Errno 2] No such file or directory: '../data/metapaths/ubu_0.8'
deepwalk --format edgelist --input ../data/metapaths/ubcabu_0.8 --output ../data/embeddings/ubcabu_0.8 --walk-length 5 --window-size 3 --number-walks 10 --representation-size 128
Traceback (most recent call last):
  File "/usr/local/bin/deepwalk", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 162, in main
    process(args)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 54, in process
    G = graph.load_edgelist(args.input, undirected=args.undirected)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/graph.py", line 249, in load_edgelist
    with open(file_) as f:
IOError: [Errno 2] No such file or directory: '../data/metapaths/ubcabu_0.8'
deepwalk --format edgelist --input ../data/metapaths/ubcibu_0.8 --output ../data/embeddings/ubcibu_0.8 --walk-length 5 --window-size 3 --number-walks 10 --representation-size 128
Traceback (most recent call last):
  File "/usr/local/bin/deepwalk", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 162, in main
    process(args)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 54, in process
    G = graph.load_edgelist(args.input, undirected=args.undirected)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/graph.py", line 249, in load_edgelist
    with open(file_) as f:
IOError: [Errno 2] No such file or directory: '../data/metapaths/ubcibu_0.8'
deepwalk --format edgelist --input ../data/metapaths/bub_0.8 --output ../data/embeddings/bub_0.8 --walk-length 5 --window-size 3 --number-walks 10 --representation-size 128
Traceback (most recent call last):
  File "/usr/local/bin/deepwalk", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 162, in main
    process(args)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 54, in process
    G = graph.load_edgelist(args.input, undirected=args.undirected)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/graph.py", line 249, in load_edgelist
    with open(file_) as f:
IOError: [Errno 2] No such file or directory: '../data/metapaths/bub_0.8'
deepwalk --format edgelist --input ../data/metapaths/bcab_0.8 --output ../data/embeddings/bcab_0.8 --walk-length 5 --window-size 3 --number-walks 10 --representation-size 128
Traceback (most recent call last):
  File "/usr/local/bin/deepwalk", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 162, in main
    process(args)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 54, in process
    G = graph.load_edgelist(args.input, undirected=args.undirected)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/graph.py", line 249, in load_edgelist
    with open(file_) as f:
IOError: [Errno 2] No such file or directory: '../data/metapaths/bcab_0.8'
deepwalk --format edgelist --input ../data/metapaths/bcib_0.8 --output ../data/embeddings/bcib_0.8 --walk-length 5 --window-size 3 --number-walks 10 --representation-size 128
Traceback (most recent call last):
  File "/usr/local/bin/deepwalk", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 162, in main
    process(args)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/__main__.py", line 54, in process
    G = graph.load_edgelist(args.input, undirected=args.undirected)
  File "/usr/local/lib/python2.7/dist-packages/deepwalk/graph.py", line 249, in load_edgelist
    with open(file_) as f:
IOError: [Errno 2] No such file or directory: '../data/metapaths/bcib_0.8'

Process finished with exit code 0

**Comment by Shodowelf** [comment]
This is an error that was reported when it was just running.

**Comment by librahu** [comment]
You need to check whether the file path is right

**Comment by Shodowelf** [comment]
If my deepwalk environment has question？If I need to change some code in it?

**Comment by librahu** [comment]
No, I think  this problem is caused by the wrong path of output file.

**Comment by Shodowelf** [comment]
What you mean is that I need to make changes in your program.

**Comment by Shodowelf** [comment]
Can you tell me which module it is?

**Comment by librahu** [comment]
我改了下代码，你重新clone下，在运行试试。

**Comment by Shodowelf** [comment]
Thank you,Are you  Chinese?

**Comment by librahu** [comment]
yes.

**Comment by Shodowelf** [comment]
Can I give you a contact number?

**Comment by librahu** [comment]
Of course.

**Comment by Shodowelf** [comment]
微信可以吗？

**Comment by Shodowelf** [comment]
17854171617，main

**Comment by librahu** [comment]
wechat?

**Comment by Shodowelf** [comment]
ok

**Comment by librahu** [comment]
I have added you.

**Comment by yenthanhle** [comment]
Hello, sir
I have a problem when I run embeddingGeneration.py
'deepwalk' is not recognized as an internal or external command,
operable program or batch file.

How should I do to solve it?
Hope you reply soon!

**Comment by Shodowelf** [comment]
Did you import the library of deepwalk?

**Comment by Shodowelf** [comment]
Did you import the library of deepwalk?

**Comment by wdtttt** [comment]
你好...我也遇到上面一个老哥的问题了
Traceback (most recent call last):
  File "C:/Users/wdt13/PycharmProjects/HERec-master/code/HERec_sl.py", line 252, in <module>
    HNERec(unum, inum, ratedim, userdim, itemdim, user_metapaths, item_metapaths, trainfile, testfile, steps, delta, beta_e, beta_h, beta_p, beta_w, beta_b, reg_u, reg_v)
  File "C:/Users/wdt13/PycharmProjects/HERec-master/code/HERec_sl.py", line 29, in __init__
    self.X, self.user_metapathdims = self.load_embedding(user_metapaths, unum)
  File "C:/Users/wdt13/PycharmProjects/HERec-master/code/HERec_sl.py", line 53, in load_embedding
    with open(sourcefile) as infile:
FileNotFoundError: [Errno 2] No such file or directory: '../data/embeddings/ubu_0.8.embedding'
麻烦请教一下您是怎么解决的

**Comment by wdtttt** [comment]
> Hellow,sir.
> In the process of running the program,I encountered the following questions,can you give me an answer?
> train_rate: 0.8
> ratedim: 10 userdim: 30 itemdim: 10
> max_steps: 100
> delta: 0.02 beta_e: 0.1 beta_h: 0.1 beta_p: 2 beta_w: 0.1 beta_b 0.1 reg_u 1.0 reg_v 1.0
> Traceback (most recent call last):
> File "E:/ler/HERec-master/code/HERec_spl.py", line 261, in
> HNERec(unum, inum, ratedim, userdim, itemdim, user_metapaths, item_metapaths, trainfile, testfile, steps, delta, beta_e, beta_h, beta_p, beta_w, beta_b, reg_u, reg_v)
> File "E:/ler/HERec-master/code/HERec_spl.py", line 29, in **init**
> self.X, self.user_metapathdims = self.load_embedding(user_metapaths, unum)
> File "E:/ler/HERec-master/code/HERec_spl.py", line 53, in load_embedding
> with open(sourcefile) as infile:
> FileNotFoundError: [Errno 2] No such file or directory: '../data/embedding/ubu_0.8.embedding'
> 
> Process finished with exit code 1
> Thank you,very much.

hello,I have met the same problem,have you solved it?

**Comment by omidjahadi** [comment]
Hello, sir
Is there any documentation or video to explain the code and it's functions?

**Comment by wdtttt** [comment]
已收到邮件，谢谢

**Comment by Hanyuzhen0826** [comment]
> Hello, sir Is there any documentation or video to explain the code and it's functions?

I also had the same problem, how did I solve it? Can you send me a copy if you have any trouble with the documentation? Thank you very much~

**Comment by wdtttt** [comment]
已收到邮件，谢谢

**Comment by Hanyuzhen0826** [comment]
> > 您好，先生。在运行程序的过程中，我遇到了以下问题，您能给我一个答案吗？ train_rate： 0.8 ratedim： 10 userdim： 30 itemdim： 10 max_steps： 100 delta： 0.02 beta_e： 0.1 beta_h： 0.1 beta_p： 2 beta_w： 0.1 beta_b 0.1 reg_u 1.0 reg_v 1.0 回溯（最近调用最后一次）： 文件 “E：/ler/HERec-master/code/HERec_spl.py”， 第 261 行， 在 HNERec（unum， inum， ratedim， userdim， itemdim， user_metapaths、item_metapaths、trainfile、testfile、steps、delta、beta_e、beta_h、beta_p、beta_w、beta_b、reg_u、reg_v） 文件 “E：/ler/HERec-master/code/HERec_spl.py”，第 29 行，**init** self。X， self.user_metapathdims = self.load_embedding（user_metapaths， unum） 文件 “E：/ler/HERec-master/code/HERec_spl.py”， 第 53 行， load_embedding open（sourcefile） 为 infile： FileNotFoundError： [Errno 2] 没有这样的文件或目录： '../data/embedding/ubu_0.8.embedding'
> > 流程完成，退出代码 1 谢谢，非常感谢。
> 
> 您好，我遇到了同样的问题，您解决了吗？
我也是，请问这个怎么解决呀？
